/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *
soma_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
    printf("%d + %d = ",argp->a,argp->b);

    result = argp->a + argp->b;

	return &result;
}
